root: true
overrides:
  # JS-Type Config Files
  - files: ['./*.{js,mjs,cjs}']
    env:
      node: true
    parserOptions:
      ecmaVersion: 'latest'
      sourceType: 'module'
    extends: ['airbnb-base', 'prettier']
    rules:
      import/extensions: 'off'
      import/no-named-default: 'off'
      import/no-extraneous-dependencies: ['error', devDependencies: true]

  # Source TypeScript Files
  - files: ['src/**/*.{ts,mts,cts,tsx}']
    env:
      browser: true
      node: true
    parser: '@typescript-eslint/parser'
    parserOptions:
      ecmaVersion: 'latest'
      sourceType: 'module'
      project: './tsconfig.eslint.json'
    extends:
      - 'airbnb'
      - 'airbnb-typescript'
      - 'airbnb/hooks'
      - 'plugin:@typescript-eslint/strict-type-checked'
      - 'prettier'
    plugins: ['@typescript-eslint']
    settings:
      import/resolver:
        webpack:
          config: 'webpack.base.cjs'
          env:
            NODE_ENV: 'production'
