extends:
  - 'stylelint-config-standard-scss'
  - 'stylelint-config-recess-order'
rules:
  # Enforces BEM-like class selector conventions.
  selector-class-pattern:
    - '^[a-z]+[0-9]{0,2}(-[a-z0-9]+)*(__[a-z0-9]+(-[a-z0-9]+)*)?(--[a-z0-9]+(-[a-z0-9]+)*)?$'
    - resolveNestedSelectors: true
  scss/at-rule-no-unknown:
    - true
    - ignoreAtRules: '/import-(?:normalize|sanitize)/'
